[package]
name = "sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
base64 = "0.22.1"
chrono = "0.4.44"
reqwest = "0.13.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
serde_json_path = "0.7.2"
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["full"] }
tower-lsp = "0.20.0"
uuid = { version = "1.22.0", features = ["v4"] }
